### ISSUE TITLE
Error not found shared.json

### ISSUE THREAD

**Issue by isayam** [proofgeist/fmdapi#15]
I'm use method list , return error
errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'shared.json',

any idea ?

**Comment by eluce2** [comment]
As a temporary fix add a blank file named `shared.json` to the root of your project and exclude it from source control. This is where the short-lived access token is stored if you're using username/password authentication. This only seems to be an issue for local development setups, as the necessary file should be auto-created instead of returning an error.

**Comment by eluce2** [comment]
This has been fixed in version 2.2.12
