### ISSUE TITLE
`refreshToken` missing from `FetchAdapterOptions` interface

### ISSUE THREAD

**Issue by nick-cheatwood7** [proofgeist/fmdapi#156]
It appears that the `refreshToken` property is missing from the `FetchAdapterOptions` interface:
https://github.com/proofgeist/fmdapi/blob/066f56730b5979ca3591191ba303526158d5c88f/src/adapters/fetch.ts#L10-L34

But is defined in the `constructor` for the `BaseFetchAdapter`:
https://github.com/proofgeist/fmdapi/blob/066f56730b5979ca3591191ba303526158d5c88f/src/adapters/fetch-base.ts#L35-L50
(the `FetchAdapter` invokes the `BaseFetchAdapter`'s constructor):
https://github.com/proofgeist/fmdapi/blob/066f56730b5979ca3591191ba303526158d5c88f/src/adapters/fetch.ts#L25

Ideally, the `FetchAdapterOptions` interface could be updated to include the `refreshToken` property (as to not introduce breaking changes to the Otto adapter):
```diff
export interface FetchAdapterOptions extends BaseFetchAdapterOptions {
  auth: {
    username: string;
    password: string;
  };
  tokenStore?: TokenStoreDefinitions;
+ refreshToken?: boolean;
}
```

For the time being, the `refreshToken` property can still be defined in the `FetchAdapter` constructor and handled properly from there, albeit by passing the proper ignore flags to Typescript.
```typescript
export const client = DataApi({
  adapter: new FetchAdapter({
    auth: {
      username: process.env.FM_USERNAME,
      password: process.env.FM_PASSWORD,
    },
    db: process.env.FM_DATABASE
    server: process.env.FM_SERVER,
    // @ts-expect-error this property exists
    refreshToken: true,
  }),
});
```

**Comment by eluce2** [comment]
perhaps I have it mislabeled in the BaseFetchAdapter, but it was intended to be a private option not exposed to the end user. I think instead the FetchAdapter should always be setting it to true in its constructor, unless there is ever a reason why you need to set it to `false`?

The OttoAdapter has been my focus so there may be other things that slipped through with the basic FetchAdapter–the token store for example. If you don't mind sharing, what is the reason you need the FetchAdapter instead of OttoFMS?

**Comment by nick-cheatwood7** [comment]
I agree that the `BaseFetchAdapter` should remain private and that the `FetchAdapter` should default `refreshToken` to `true` in its constructor.  I can foresee some use-cases in which I might want to set `refreshToken` to `false`, though. So having the option to provide that in the `FetchAdapter` constructor would still be preferred. For example, when creating a "throwaway" client (maybe for handling user auth) when I don't care about refreshing the token.

The reason I need the `FetchAdapter` and not the `OttoAdapter` is quite simple– some FileMaker Servers aren't running Otto. I think the `OttoAdapter` would be ideal, but I'm very often working on solutions for FileMaker databases/servers without Otto.

**Comment by eluce2** [comment]
The refresh token option will only attempt to get a new token if the old one came back as expired though, so if you were creating a throw-away client, you could call the disconnect method and just never call it again and it wouldn't refresh.

Did you know that the newest version of [OttoFMS](https://www.proofgeist.com/products/filemaker-data-migration-tool-ottofms-superpowers/) is completely free? If you need help installing or convincing your clients that it's worth installing, please reach out on our [forums](https://community.ottomatic.cloud/c/ottofms/6). We'd love to hear about your use case to make sure it could be supported if it's not already. It's something that we require on all our client's servers because of the vast utility that it provides

**Comment by nick-cheatwood7** [comment]
Good point. I'd say leave the `refreshToken` as defaulting to `true` in the constructor.

Re: Otto FMS– Yes, I did! In. a perfect world, we could have OttoFMS installed alongside every FileMaker server we deploy to. I'll check the forum, thanks for passing that along.
